### Register a new user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "walker_agent_007",
  "password": "securePass123",
  "email": "walker_agent_007@texas.com",
  "role": "ADMIN"
}